version: "3.9"
services:
  node-one:
    image: &node_image nutsfoundation/nuts-node:v2.0.4
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    ports:
      - "1323:1323"
    volumes:
      - "./node-data/nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "./node-data/kikv.ldjson:/opt/nuts/jsonld/kikv.ldjson:ro"
      - "./node-data/one/node:/opt/nuts/data"
  node-two:
    image: *node_image
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
      NUTS_BOOTSTRAPNODES: node-one:5555
    ports:
      - "2323:1323"
    volumes:
      - "./node-data/nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "./node-data/kikv.ldjson:/opt/nuts/jsonld/kikv.ldjson:ro"
      - "./node-data/two/node:/opt/nuts/data"
  node-three:
    image: *node_image
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
      NUTS_BOOTSTRAPNODES: node-one:5555
    ports:
      - "3323:1323"
    volumes:
      - "./node-data/nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "./node-data/kikv.ldjson:/opt/nuts/jsonld/kikv.ldjson:ro"
      - "./node-data/three/node:/opt/nuts/data"
  admin-one:
    image: &admin_image nutsfoundation/nuts-registry-admin-demo:master
    ports:
      - "1303:1303"
    environment:
      NUTS_DBFILE: "/app/data/registry-admin.db"
      NUTS_CUSTOMERSFILE: "/app/data/customers.json"
      NUTS_NUTSNODEADDR: "http://node-one:1323"
      NUTS_CREDENTIALS_USERNAME: "demo@nuts.nl"
      NUTS_CREDENTIALS_PASSWORD: "demo"
    volumes:
      - "./node-data/one/admin:/app/data"
    depends_on:
      - node-one
  admin-two:
    image: *admin_image
    ports:
      - "2303:1303"
    environment:
      NUTS_DBFILE: "/app/data/registry-admin.db"
      NUTS_CUSTOMERSFILE: "/app/data/customers.json"
      NUTS_NUTSNODEADDR: "http://node-two:1323"
      NUTS_CREDENTIALS_USERNAME: "demo@nuts.nl"
      NUTS_CREDENTIALS_PASSWORD: "demo"
    volumes:
      - "./node-data/two/admin:/app/data"
    depends_on:
      - node-two
  admin-three:
    image: *admin_image
    ports:
      - "3303:1303"
    environment:
      NUTS_DBFILE: "/app/data/registry-admin.db"
      NUTS_CUSTOMERSFILE: "/app/data/customers.json"
      NUTS_NUTSNODEADDR: "http://node-three:1323"
      NUTS_CREDENTIALS_USERNAME: "demo@nuts.nl"
      NUTS_CREDENTIALS_PASSWORD: "demo"
    volumes:
      - "./node-data/three/admin:/app/data"
    depends_on:
      - node-three
  graphdb:
    container_name: graphdb
    image: reneh/triplestore:9.10.0-free
    restart: unless-stopped
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - 7200:7200
    volumes:
      - ./triplestore/database:/opt/graphdb/home
