concept: validatedquery
credentialType: ValidatedQueryCredential
public: true
indices:
  - name: index_id
    parts:
      - path: id
  - name: index_issuer
    parts:
      - path: issuer
  - name: index_subject
    parts:
      - path: credentialSubject.id
        alias: subject
  - name: index_query
    parts:
      - path: credentialSubject.validatedQuery.profile
        alias: profile
        tokenizer: whitespaceOrExact
        transformer: cologne
      - path: credentialSubject.validatedQuery.ontology
        alias: ontology
        tokenizer: whitespaceOrExact
        transformer: cologne
template: |
    {
      "id": "<<id>>",
      "issuer": "<<issuer>>",
      "type": "ValidatedQueryCredential",
      "subject": "<<credentialSubject.id>>",
      "validatedQuery": {
        "profile": "<<credentialSubject.validatedQuery.profile>>",
        "ontology": "<<credentialSubject.validatedQuery.ontology>>"
        "sparql": "<<credentialSubject.validatedQuery.sparql>>"
      }
    }
