routes:
  -
    id: fhir_server
    uri: /*
    upstream:
      nodes:
        "hapi:8080": 1
      type: roundrobin
    plugin_config_id: nuts-zorgtoepassing-authz

plugin_configs:
  - id: nuts-zorgtoepassing-authz
    plugins:
      openid-connect:
        client_id: "client_id_todo"
        client_secret: "client_secret_todo"
        discovery: "discovery_todo"
        introspection_endpoint: "http://nutsnode:1323/internal/auth/v2/accesstoken/introspect"
        bearer_only: true
        realm: "master"
        introspection_endpoint_auth_method: none
      opa:
        host: "http://policy-agent:8181"
        policy: geboortezorg

#END
