### Setup: create a new did:web for the hospital
POST http://localhost:8081/internal/vdr/v2/did
Content-Type: application/json

{
  "id": "hospital"
}

> {% client.global.set('hospitalDID', response.body.id) %}

### Issue a NutsOrganizationCredential
# Set the expiration date to 1 year
< {% client.global.set('credentialExpirationDate', new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 365).toISOString()) %}
POST http://localhost:8081/internal/vcr/v2/issuer/vc
Content-Type: application/json

{
    "type": "NutsOrganizationCredential",
    "issuer": "{{hospitalDID}}",
    "expirationDate": "{{credentialExpirationDate}}",
    "credentialSubject": {
        "id": "{{hospitalDID}}",
        "organization": {
            "name": "Hospital",
            "city": "Arnhem"
        }
    }
}

> {%
    client.global.set('hospitalVC', JSON.stringify(response.body))
%}

### Load issues NutsOrganizationCredential into holder's wallet
POST http://localhost:8081/internal/vcr/v2/holder/{{hospitalDID}}/vc
Content-Type: application/json

{{hospitalVC}}

### Activate HomeMonitoring Discovery Service for the DID
POST http://localhost:8081/internal/discovery/v1/dev:HomeMonitoring2024/{{hospitalDID}}

