services:
  hapi:
    image: hapiproject/hapi:v6.10.1
    ports:
      - "7080:8080" # port is exported to load test data
    environment:
      - hapi.fhir.fhir_version=DSTU3
      - hapi.fhir.partitioning.allow_references_across_partitions=false
    networks:
      - nuts-deployment-apigateway
  resource-authz-server:
    build: resource-authz
    ports:
      - "9000:8080" # port is exposed to load test data
    networks:
      - nuts-deployment-apigateway
    depends_on:
      - hapi
      - nutsnode
  nutsnode:
    image: nutsfoundation/nuts-node:6.0.0-alpha.1
    ports:
      - "8081:8081" # port exposed for loading test data (create DIDs and VCs, requesting access token)
      - "8080:8080"
    volumes:
      - "./nutsnode/policy:/opt/nuts/policy"
      # did:web resolver uses the OS CA bundle, but e2e tests use a self-signed CA which can be found in truststore.pem
      # So we need to mount that file to the OS CA bundle location, otherwise did:web resolving will fail due to untrusted certs.
      - "./nutsnode/truststore.pem:/etc/ssl/certs/Nuts_RootCA.pem:ro"
    environment:
      # NUTS_URL being the API Gateway might look weird, but it's actually the "outside facing" interface for the Nuts node,
      # since it needs TLS which is handled by APISIX in this setup.
      - NUTS_URL=https://api-gateway:9443
      - NUTS_STRICTMODE=false
      - NUTS_VERBOSITY=debug
      - NUTS_HTTP_INTERNAL_ADDRESS=:8081
      - NUTS_POLICY_DIRECTORY=/opt/nuts/policy
      - NUTS_AUTH_CONTRACTVALIDATORS=dummy
    networks:
      - nuts-deployment-apigateway
networks:
  nuts-deployment-apigateway:
    name: nuts-deployment-apigateway
    external: true